export const KITS = [
  {
    id: "kit-principiante",
    name: "Kit Principiante",
    description: "Todo lo que necesitás para tu primera salida de camping",
    price: 450000,
    discountPrice: 380000,
    image: "/images/products/kit-principiante.jpg",
    items: [
      "Carpas 2-3 personas",
      "Sábanas impermeables",
      "Lámpara LED",
      "Mesa plegable",
      "Silla camping",
    ],
    badge: "Más vendido",
  },
  {
    id: "kit-pesca",
    name: "Kit Pesca Completo",
    description: "Equipo completo para tus jornadas de pesca",
    price: 680000,
    discountPrice: 590000,
    image: "/images/products/kit-pesca.jpg",
    items: [
      "Caña de pesca telescópica",
      "Carretel con línea",
      "Set de señuelos",
      "Caja de aparejos",
      "Silla plegable",
      "Sombrero",
    ],
    badge: null,
  },
  {
    id: "kit-familia",
    name: "Kit Familia",
    description: "Para disfrutar en familia al aire libre",
    price: 950000,
    discountPrice: 790000,
    image: "/images/products/kit-familia.jpg",
    items: [
      "Carpas 4-6 personas",
      "2 mesas plegables",
      "4 sillas camping",
      "Lámpara LED portátil",
      "Cocineta de camping",
      "Set de utensilios",
    ],
    badge: "Popular",
  },
  {
    id: "kit-aventura",
    name: "Kit Aventura Extrema",
    description: "Equipo profesional para los más aventureros",
    price: 1200000,
    discountPrice: 1050000,
    image: "/images/products/kit-aventura.jpg",
    items: [
      "Carpas resistente 4 estaciones",
      "Sábanas impermeables premium",
      "Lámpara de alta potencia",
      "Cocineta multi-fuel",
      "Brújula GPS",
      "Mochila técnica 60L",
      "Kit de supervivencia",
    ],
    badge: "Pro",
  },
]
